version: "3.8"

services:
    neo4j-apoc:
        image: graphfoundation/ongdb:latest
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes: 
            - neo4j-data:/data
            - neo4j-plugins:/plugins
            - C:\import:/var/lib/neo4j/import
        environment:
            NEO4J_apoc_export_file_enabled: 'true'
            NEO4J_apoc_import_file_enabled: 'true'
            NEO4J_apoc_import_file_use__neo4j__config: 'true'
            NEO4JLABS_PLUGINS: '["apoc"]'


volumes:
     neo4j-data:
     neo4j-plugins:
  
  