name: RedditStatistics
channels:
    - conda-forge
dependencies:
    - python=3.8.5
    - pylint=2.6.0
    - pandas=1.1.3
    - matplotlib=3.3.3
    - seaborn=0.11.1
    - pip:
          - python-settings==0.2.2
