name: RedditStatistics
channels:
    - conda-forge
dependencies:
    - python=3.9.2
    - pylint=2.7.2
    - pandas=1.2.3
    - matplotlib=3.3.4
    - seaborn=0.11.1
    - jupyter
    - jupyterlab
    - pip
    - pip:
          - python-settings==0.2.2
