name: build-sbt

on:
  workflow_call:

jobs:
  build-sbt:
    name: Reddit Graph Stream Pipeline CI with SBT
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RedditDatasetStreamPipeline

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    
    - name: Run tests
      run: sbt test

    - name: Build Zip Package witha all dependencies
      run: sbt universal:packageBin

    - name: Rename artifact
      run: mv target/universal/redditdatasetstreampipeline-0.1.zip target/universal/redditdatasetstreampipeline.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: redditdatasetstreampipeline
        path: RedditDatasetStreamPipeline/target/universal/redditdatasetstreampipeline.zip
        if-no-files-found: error


  build-gradle:
    name: RedditGraph CI with Gradle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RedditGraph

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test
      run: ./gradlew test

    - name: Build fat JAR
      run: ./gradlew shadowjar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RedditGraph
        path: RedditGraph/build/libs/RedditGraph.jar
        if-no-files-found: error
