name: Release Build

on:
  push:
    branches: [ master ]


jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
      - name: Download a Build Artifact RedditGraph
        uses: actions/download-artifact@v4.1.7
        with:
          name: RedditGraph
          
      - name: Download a Build Artifact redditdatasetstreampipeline
        uses: actions/download-artifact@v4.1.7
        with:
          name: redditdatasetstreampipeline
          
      - name: Create release latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            redditdatasetstreampipeline.zip
            RedditGraph.jar
  
