name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run tests
      run: sbt test
    - name: Build JAR with dependencies
      run: sbt assembly
    - uses: actions/upload-artifact@v2
      with:
        name: rdsp.jar
        path: target/scala-2.13/rdsp.jar
