name: Scala CI

on:
  push:
    branches: [ "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run tests
      run: sbt test
    - name: Build Zip Package witha all dependencies
      run: sbt universal:packageBin
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: redditdatasetstreampipeline.zip
        path: target/universal/redditdatasetstreampipeline-0.1.zip
